# Lab3: Recommendation System and BERT
## 1. Recommendation system overview
A recommendation system predicts what items a user may like and returns a ranked list of items. Examples:
| Platform           | User              | Item                  | Example feedback signals                             | Recommendation goal                      |
| ------------------ | ----------------- | --------------------- | ---------------------------------------------------------------------------- | ---------------------------------------- |
| Netflix            | viewer            | movie/show            | watch history, watch time, ratings, likes/dislikes, skips, searches          | what to watch next                       |
| Amazon             | customer          | product               | clicks, purchases, add-to-cart, wish lists, reviews, ratings, search queries | what to buy next                         |
| Spotify            | listener          | song/playlist/podcast | listening history, skips, replays, likes, playlist saves, follows            | what to listen to next                   |
| YouTube            | viewer            | video                 | clicks, watch time, likes/dislikes, comments, subscriptions, search history  | what to watch next                       |
| TikTok / Instagram | viewer            | short video/post      | views, watch time, replays, likes, shares, comments, follows, skips          | what content to show next                |
| LinkedIn           | professional user | job/post/connection   | clicks, applications, profile views, follows, reactions, connection requests | what jobs, posts, or people to recommend |


Recommendation systems may utilize both explicit feedback and implicit feedback as signals:
| Explicit feedback | Implicit feedback |
| ----------------- | ----------------- |
| Star rating       | Click             |
| Review score      | Watch time        |
| Like/dislike      | Add to cart       |
| Survey response   | Purchase          |

There are 3 common recommendation approaches
1. Popularity baseline
2. Collaborative filltering
3. Content-based recommendation


## 2. Recommendation on MovieLens 1M data
### 2.1. AWS S3
Amazon S3 (Simple Storage Service) is AWS’s object storage service.
- Object = data + metadata

Here are some key terms:

- **Bucket**: the top-level container (globally unique name, for example, `de300-tutorial-data`).

- Object: one stored file (e.g., `movies.dat`).

- Key: the “path-like name” of the object inside a bucket (e.g., `s3://de300-tutorial-data/datasets/movielens/ml-1m.zip`).

- Prefix: the leading part of a key used for organization. S3 doesn’t have real folders; the console shows folder-like views using prefixes.

We may upload/download/modify files on s3 through AWS CLI tool (which may be installed through instruction on [AWS CLI installation](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html)).

Before we use AWS CLI to get access to data on S3, we should set up credentials on the device (your own laptop or EC2). One of the ways to do so is go to the [https://nu-sso.awsapps.com/](https://nu-sso.awsapps.com/), click `Access Keys` and copy AWS Environmental Variables, e.g.,
```
export AWS_ACCESS_KEY_ID="ASIAYAAO5HRMPUB3MCSY"
export AWS_SECRET_ACCESS_KEY="rfQO99t/exgmgg96UZPlgwiPdQeIvDH+TwdpMmYZ"
export AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjED4aCXVzLWVhc3QtMiJHMEUCIQDIgnu1hQVRJkVO5hNC2nwZoymcocar0UBm/iLYAwce/gIgMAg+597W6iSiSjGf79zufe3O+iTtUTFgRvXA+EIs9H0q7QIIBxAAGgw1NDk3ODcwOTAwMDgiDNxFudXUE23299Ym3yrKAsauHL8Z7rTAIL25QvZi4zYbhMv7yUMtQ/uQlrMWa3Hqmec202sYY3iyaycTTrhG86olYRddLYBzqB5Voh9+VTcWgeTSOpZG86AUNoULPkFGLBVFDaokpqdfWexNgsSzIAPnya9MK0Rd7MKmeTWrDPZVx1BCwW9OkDiH6kCYBbfZU6BtkdkJ3Evsmo8Bbb+8myGzqMIoQPcekcDjBQ1Gf1TBh9hvsocxVUA/DX3NrShNImKLXW+XTExn2Vi3ZFrCof+35gVhh1L3s6Z16gDNCOAr1LYc/MjBdR/RSSTKCVgkCaioOd+hRxTpNz1IPMCnuubbcST014WUFgASQDNUQ6QOpYcegbwNjjyq4pA6kzQBoewNThZ9x1meusGz7uJcDBmqGJDimEV88Wa3ucBQSgHpfwheoeJrPL2yjyLp5R7GRdoeGOA6k/POZzCd14nMBjqlAWaFsCTsj3+5QN/rsUmUoIq8qyMPpanSn9P191MA8hIykQquGiqhDkjF3ctIBSgS1Rv0JdOd7SJsEK7iOzBV4JkSQ9Mr6vs5UuozFGWMIJlS0F2bmVNhJuD6efIgdlcqeI58mc8nMxmiFYNiWivQQopMHSFgsHnTu9Q+7hutm2jMzmsCBrAxFw12jGG8ab0MwB54V7OUXQvhe1TTeeeBdos9jt4dUA=="
```

Some commands that are frequently used:
1. List all objects under a prefix
   ```
   aws s3 ls s3://dinglin-spring26/
   ```
2. Copy ONE object from S3 to local
   ```
   aws s3 cp s3://dinglin-spring26/lab4/ml-1m/movies.dat ./movies.dat
   ```

3. Copy a “folder” (prefix) recursively
   ```
   aws s3 cp s3://dinglin-spring26/lab4/ml-1m/ ./lab4-data/ --recursive
   ```

4. Copy files and folders among different buckets
   ```
   aws s3 cp s3://dinglin-spring26/lab4/ml-1m/movies.dat s3://DEST_BUCKET/path/to/movies.dat
   aws s3 cp s3://dinglin-spring26/lab4/ml-1m/ s3://DEST_BUCKET/some/prefix/ --recursive
   ```

### 2.2. Dataset Intro
MovieLens 1M is a classic benchmark dataset for recommender systems released by the GroupLens Research Project. It contains 1,000,209 ratings (1–5 stars, whole-star only) from 6,040 users on movie IDs up to 3,952, and each user has at least 20 ratings.

### 2.3. Data Loading
We will read `ratings.dat` and `movies.dat` from the `ml-1m/` folder. These files use `::` as a delimiter, so we set `engine='python'` in `pandas.read_csv`.

- ratings.dat: (user_id, movie_id, rating, timestamp)
- movies.dat: (movie_id, title, genres)

In [2]:
import torch.nn.functional as F
import torch
import os
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
DATA_DIR = "/content/drive/My Drive/Data_Eng_300/ml-1m/"
os.listdir(DATA_DIR)

['README', 'movies.dat', 'ratings.dat', 'users.dat']

In [5]:
import pandas as pd

# DATA_DIR = "/Users/dinglin/Desktop/courses/Data_Eng300/Winter2026/labs/lab4/ml-1m/"
RATINGS_FILE = DATA_DIR + "ratings.dat"
MOVIES_FILE = DATA_DIR + "movies.dat"

ratings = pd.read_csv(RATINGS_FILE, sep="::", engine="python",
                      names=["user_id","movie_id","rating","timestamp"])
movies  = pd.read_csv(MOVIES_FILE,  sep="::", engine="python",
                      names=["movie_id","title","genres"], encoding="latin-1")

ratings.head(), movies.head()

(   user_id  movie_id  rating  timestamp
 0        1      1193       5  978300760
 1        1       661       3  978302109
 2        1       914       3  978301968
 3        1      3408       4  978300275
 4        1      2355       5  978824291,
    movie_id                               title                        genres
 0         1                    Toy Story (1995)   Animation|Children's|Comedy
 1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
 2         3             Grumpier Old Men (1995)                Comedy|Romance
 3         4            Waiting to Exhale (1995)                  Comedy|Drama
 4         5  Father of the Bride Part II (1995)                        Comedy)

Implicit recommendation models usually need positive interactions rather than 1–5 star ratings. Here we treat ratings ≥ 4 as a positive signal and create a binary column value=1.0

In [6]:
pos = ratings[ratings["rating"] >= 4].copy()
pos["value"] = 1.0

To evaluate recommendation, we hold out each user’s most recent positive interaction as the test item (using timestamp). The remaining positives become training data.

In [7]:
pos = pos.sort_values(["user_id","timestamp"])
test = pos.groupby("user_id").tail(1)
train = pos.drop(test.index)

train.shape, test.shape

((569243, 5), (6038, 5))

Before building sophisticated models, it’s useful to compute a simple baseline: recommend the most frequently liked movies in the training set. This gives you a sanity check for your pipeline.

In [8]:
top_movies = train.groupby("movie_id")["value"].sum().sort_values(ascending=False)
top10 = top_movies.head(10).index.tolist()
movies[movies["movie_id"].isin(top10)][["movie_id","title","genres"]]

,movie_id,title,genres
257,260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi
589,593,"Silence of the Lambs, The (1991)",Drama|Thriller
604,608,Fargo (1996),Crime|Drama|Thriller
1178,1196,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Drama|Sci-Fi|War
1180,1198,Raiders of the Lost Ark (1981),Action|Adventure
1192,1210,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Romance|Sci-Fi|War
1959,2028,Saving Private Ryan (1998),Action|Drama|War
2502,2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller
2693,2762,"Sixth Sense, The (1999)",Thriller
2789,2858,American Beauty (1999),Comedy|Drama

### 2.4. ALS (Collborative Filltering)
Many recommenders (including `implicit ALS`) expect a sparse matrix. We map raw IDs to contiguous indices:

- user2idx: user_id → row index
- item2idx: movie_id → column index
Then we create a sparse matrix X_ui with shape [num_users, num_items].

In [9]:
import numpy as np
from scipy.sparse import coo_matrix

user_ids = train["user_id"].unique()
movie_ids = train["movie_id"].unique()

user2idx = {u:i for i,u in enumerate(user_ids)}
movie_ids = np.array(movie_ids)  # ensure it's a numpy array
item2idx = {int(m): i for i, m in enumerate(movie_ids)}
idx2item = {i: int(m) for i, m in enumerate(movie_ids)}

rows = train["user_id"].map(user2idx).to_numpy()
cols = train["movie_id"].map(item2idx).to_numpy()
data = train["value"].to_numpy().astype(np.float32)
X_ui = coo_matrix((data, (rows, cols)), shape=(len(user_ids), len(movie_ids))).tocsr()

In [1]:
!pip install implicit

Collecting implicit
  Downloading implicit-0.7.2.tar.gz (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/70.3 kB 2.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from implicit) (2.0.2)
Requirement already satisfied: scipy>=0.16 in /usr/local/lib/python3.12/dist-packages (from implicit) (1.16.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from implicit) (4.67.3)
Requirement already satisfied: threadpoolctl in /usr/local/lib/python3.12/dist-packages (from implicit) (3.6.0)
Building wheels for collected packages: implicit
  Building wheel for implicit (pyproject.toml) ... done
  Created wheel for implicit: filename=implicit-0.7.2-cp312-cp312-linux_x86_64.whl size=933264 sha256=82a67000582f46d94bc6d65571a003ad1a7267869ae638f1a922ad7d6a64b25d
  Stored in directory: /root/.cache/pip/wheels/b2/00/4f/9ff8af07a0a53ac6007ea5d739da19cfe147a2df542b6899f8
Successfully built implicit
Installing collected packages: implicit
Successfully installed implicit-0.7.2

In [10]:
import implicit

model = implicit.als.AlternatingLeastSquares(
    factors=64, regularization=0.01, iterations=20
)

# implicit expects item-user matrix
model.fit(X_ui)

/usr/local/lib/python3.12/dist-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 2 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()

  0%|          | 0/20 [00:00<?, ?it/s]

In [11]:
u = int(user_ids[0])
u_idx = int(user2idx[u])

# IMPORTANT: pass X_ui[u_idx] (1 row), not the full X_ui
recs = model.recommend(u_idx, X_ui[u_idx], N=10)

# Handle implicit returning either (ids, scores) OR list of pairs
if isinstance(recs, tuple) and len(recs) == 2:
    item_ids, scores = recs
else:
    item_ids = [i for i, s in recs]
    scores  = [s for i, s in recs]

rec_movie_ids = [idx2item[int(i)] for i in item_ids]

rec_df = movies.set_index("movie_id").loc[rec_movie_ids][["title", "genres"]].reset_index()
rec_df["score"] = list(scores)
rec_df

,movie_id,title,genres,score
0,364,"Lion King, The (1994)",Animation|Children's|Musical,0.660796
1,2081,"Little Mermaid, The (1989)",Animation|Children's|Comedy|Musical|Romance,0.414326
2,318,"Shawshank Redemption, The (1994)",Drama,0.401152
3,1225,Amadeus (1984),Drama,0.386217
4,34,Babe (1995),Children's|Comedy|Drama,0.382858
5,3471,Close Encounters of the Third Kind (1977),Drama|Sci-Fi,0.371557
6,953,It's a Wonderful Life (1946),Drama,0.363862
7,2716,Ghostbusters (1984),Comedy|Horror,0.360213
8,2085,101 Dalmatians (1961),Animation|Children's,0.336026
9,1259,Stand by Me (1986),Adventure|Comedy|Drama,0.323587

### 2.5. Evaluation: Recall@K and NDCG@K
We evaluate each user by checking whether the held-out test movie appears in the top-K recommendations:

- Recall@K: fraction of users whose held-out item is retrieved in top-K.
- NDCG@K: like Recall@K, but gives higher credit when the item appears closer to rank 1.

In [12]:
import math

def ndcg_at_k(rank, k):
    if rank is None or rank >= k:
        return 0.0
    return 1.0 / math.log2(rank + 2)

def _get_rec_items(recs):
    # implicit may return (item_ids, scores) OR list of (id, score)
    if isinstance(recs, tuple) and len(recs) == 2:
        item_ids = recs[0]
        return [int(i) for i in item_ids]
    else:
        return [int(i) for i, _ in recs]

def eval_model(model, X_ui, test_df, K=10):
    hits, ndcgs, n = 0, 0.0, 0
    for u, gt in zip(test_df["user_id"], test_df["movie_id"]):
        if (u not in user2idx) or (gt not in item2idx):
            continue

        u_idx = int(user2idx[u])

        # IMPORTANT: pass only this user's row
        recs = model.recommend(u_idx, X_ui[u_idx], N=K)

        rec_items = _get_rec_items(recs)
        gt_idx = int(item2idx[gt])

        if gt_idx in rec_items:
            hits += 1
            ndcgs += ndcg_at_k(rec_items.index(gt_idx), K)

        n += 1

    return {"Recall@K": hits / max(n, 1), "NDCG@K": ndcgs / max(n, 1), "Users": n}

eval_model(model, X_ui, test, K=10)

{'Recall@K': 0.09396751740139211, 'NDCG@K': 0.04696169281938887, 'Users': 6034}

### 2.6. Content Embedding with BERT Model

In [13]:
movies["text"] = movies["title"].fillna("") + " [SEP] " + movies["genres"].fillna("")
movies["text"].head()

0    Toy Story (1995) [SEP] Animation|Children's|Co...
1    Jumanji (1995) [SEP] Adventure|Children's|Fantasy
2         Grumpier Old Men (1995) [SEP] Comedy|Romance
3          Waiting to Exhale (1995) [SEP] Comedy|Drama
4      Father of the Bride Part II (1995) [SEP] Comedy
Name: text, dtype: object

In [14]:
import torch
from transformers import AutoTokenizer, AutoModel

device = "cuda" if torch.cuda.is_available() else "cpu"
tok = AutoTokenizer.from_pretrained("bert-base-uncased")
bert = AutoModel.from_pretrained("bert-base-uncased").to(device)
bert.eval()

@torch.no_grad()
def encode_texts(texts, batch_size=64, max_len=64):
    embs = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        inp = tok(batch, padding=True, truncation=True, max_length=max_len, return_tensors="pt").to(device)
        out = bert(**inp).last_hidden_state[:,0,:]  # [CLS]
        embs.append(out.cpu())
    return torch.cat(embs, dim=0)

item_emb = encode_texts(movies["text"].tolist())
item_emb.shape

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

torch.Size([3883, 768])

### 2.6. Save item embedding as tensor

In [16]:
save_path = "/content/drive/My Drive/Data_Eng_300/ml-1m/item_emb.pt"
torch.save(item_emb, save_path)

# later
item_emb2 = torch.load(save_path, map_location="cpu")
print(item_emb2.shape)

torch.Size([3883, 768])

In [18]:
payload = {
    "item_emb": item_emb,                      # [num_items, hidden_dim]
    "movie_id": movies["movie_id"].to_numpy(), # same order as embeddings
}
torch.save(payload, "/content/drive/My Drive/Data_Eng_300/ml-1m/item_emb_with_ids.pt")

# later
obj = torch.load("/content/drive/My Drive/Data_Eng_300/ml-1m/item_emb_with_ids.pt", map_location="cpu", weights_only=False)
item_emb = obj["item_emb"]
movie_id = obj["movie_id"]

In [19]:
import torch.nn.functional as F

# normalize for cosine similarity
E = F.normalize(item_emb, p=2, dim=1)

movieid_to_row = {mid:i for i,mid in enumerate(movies["movie_id"].tolist())}

def similar_movies(movie_id, topk=10):
    i = movieid_to_row[movie_id]
    sims = (E @ E[i]).numpy()
    top = sims.argsort()[::-1][1:topk+1]  # exclude itself
    return movies.iloc[top][["movie_id","title","genres"]]

similar_movies(movie_id=1, topk=10)  # Toy Story is movie_id=1 in ml-1m

,movie_id,title,genres
3045,3114,Toy Story 2 (1999),Animation|Children's|Comedy
3682,3751,Chicken Run (2000),Animation|Children's|Comedy
1050,1064,Aladdin and the King of Thieves (1996),Animation|Children's|Comedy
584,588,Aladdin (1992),Animation|Children's|Comedy|Musical
2286,2355,"Bug's Life, A (1998)",Animation|Children's|Comedy
1743,1806,Paulie (1998),Adventure|Children's|Comedy
2069,2138,Watership Down (1978),Animation|Children's|Drama|Fantasy
591,595,Beauty and the Beast (1991),Animation|Children's|Musical
2072,2141,"American Tail, An (1986)",Animation|Children's|Comedy
451,455,Free Willy (1993),Adventure|Children's|Drama

In [20]:
from collections import defaultdict
import numpy as np

liked = train.groupby("user_id")["movie_id"].apply(list).to_dict()

def recommend_for_user_content(user_id, topk=10):
    mids = liked.get(user_id, [])
    mids = [m for m in mids if m in movieid_to_row]
    if not mids:
        return None
    rows = [movieid_to_row[m] for m in mids]
    u = E[rows].mean(dim=0, keepdim=True)
    sims = (E @ u[0]).numpy()
    # filter already seen
    seen_rows = set(rows)
    candidates = [i for i in sims.argsort()[::-1] if i not in seen_rows]
    top = candidates[:topk]
    return movies.iloc[top][["movie_id","title","genres"]]

recommend_for_user_content(user_ids[0], topk=10)

      movie_id                 title           genres
3038      3107      Backdraft (1991)     Action|Drama
3099      3168     Easy Rider (1969)  Adventure|Drama
1096      1112   Palookaville (1996)     Action|Drama
651        657    Yankee Zulu (1994)     Comedy|Drama
1885      1954          Rocky (1976)     Action|Drama
2857      2926      Hairspray (1988)     Comedy|Drama
2508      2577      Metroland (1997)     Comedy|Drama
3096      3165  Boiling Point (1993)     Action|Drama
533        537         Sirens (1994)     Comedy|Drama
3457      3526     Parenthood (1989)     Comedy|Drama

In [21]:
# item2idx maps movie_id -> item_idx used by X_ui / eval_model
idx2item = {i:m for m,i in item2idx.items()}

# Build a matrix of embeddings in item-index order (0..num_items-1)
# Assumes you have:
# - E: normalized embeddings for ALL movies in `movies` dataframe (same order as movies rows)
# - movieid_to_row: mapping movie_id -> row index in `movies`/E
# If you don't already have E/movieid_to_row, see the note below.

# If you have `item_emb` as torch tensor [num_movies_all, 768]:
E_all = F.normalize(item_emb, p=2, dim=1)

movieid_to_row = {mid:i for i,mid in enumerate(movies["movie_id"].tolist())}

num_items = len(item2idx)
dim = E_all.shape[1]
E_items = torch.empty((num_items, dim), dtype=E_all.dtype)

missing = 0
for item_idx in range(num_items):
    mid = idx2item[item_idx]
    row = movieid_to_row.get(mid, None)
    if row is None:
        missing += 1
        E_items[item_idx] = 0
    else:
        E_items[item_idx] = E_all[row]

print("missing movies:", missing, "out of", num_items)

missing movies: 0 out of 3530

## Lab Assignment
1. Complete the recommend functions powered by BERT Content Embedding.
2. Try at least 2 different pre-trained model for embedding and test the model performance.

In [22]:
class BertContentModel:
    def __init__(self, E_items):
        # E_items: torch tensor [num_items, dim], already normalized
        self.E = F.normalize(E_items, p=2, dim=1)

    def recommend(self, u_idx, X_ui, N=10):
        # Get items user interacted with from sparse matrix row
        seen = X_ui.indices

        # Edge cases: the user has no seen movies
        if len(seen) == 0:
          return (np.array([]), np.array([]))

        # User embedding = mean of seen item embeddings
        user_emb = self.E[seen].mean(dim=0)

        # Top-N
        scores = (self.E @ user_emb).numpy()
        for s in seen:
          scores[s] = -1.0
        top_idx = scores.argsort()[::-1][:N]
        top_scores = scores[top_idx]

        return [(int(i), float(top_scores[j])) for j, i in enumerate(top_idx)]

In [23]:
bert_model = BertContentModel(E_items)

In [24]:
results_bert = eval_model(bert_model, X_ui, test, K=10)
print("BERT base results:", results_bert)

BERT base results: {'Recall@K': 0.01557838912827312, 'NDCG@K': 0.007848329700857354, 'Users': 6034}

In [25]:
#second model - DistilBERT
tok2 = AutoTokenizer.from_pretrained("distilbert-base-uncased")
bert2 = AutoModel.from_pretrained("distilbert-base-uncased").to(device)
bert2.eval()

@torch.no_grad()
def encode_texts_model(texts, tokenizer, model, batch_size=64, max_len=64):
  embs = []
  for i in range(0, len(texts), batch_size):
    batch = texts[i:i+batch_size]
    inp = tokenizer(batch, padding=True, truncation=True, max_length=max_len, return_tensors="pt").to(device)
    out = model(**inp).last_hidden_state[:, 0, :]
    embs.append(out.cpu())
  return torch.cat(embs, dim=0)

item_emb2 = encode_texts_model(movies["text"].tolist(), tok2, bert2)
print("DistilBERT embeddings shape:", item_emb2.shape)

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_layer_norm.bias   | UNEXPECTED |  |
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_transform.bias    | UNEXPECTED |  |
vocab_projector.bias    | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

DistilBERT embeddings shape: torch.Size([3883, 768])

In [26]:
#E_items for DistilBERT
E_all2 = F.normalize(item_emb2, p=2, dim=1)

E_items2 = torch.empty((num_items, E_all2.shape[1]), dtype=E_all2.dtype)
for item_idx in range(num_items):
  mid = idx2item[item_idx]
  row = movieid_to_row.get(mid, None)
  if row is None:
    E_items2[item_idx] = 0
  else:
    E_items2[item_idx] = E_all2[row]

distilbert_model = BertContentModel(E_items2)
results_distil = eval_model(distilbert_model, X_ui, test, K=10)
print("DistilBERT results:", results_distil)

DistilBERT results: {'Recall@K': 0.01690420947961551, 'NDCG@K': 0.007356312196454116, 'Users': 6034}

In [27]:
#Third Model - ALBERT
tok3 = AutoTokenizer.from_pretrained("albert-base-v2")
bert3 = AutoModel.from_pretrained("albert-base-v2").to(device)
bert3.eval()

item_emb3 = encode_texts_model(movies["text"].tolist(), tok3, bert3)
print("ALBERT embeddings shape:", item_emb3.shape)

config.json:   0%|          | 0.00/684 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/760k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/47.4M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertModel LOAD REPORT from: albert-base-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
predictions.LayerNorm.weight | UNEXPECTED |  |
predictions.decoder.bias     | UNEXPECTED |  |
predictions.LayerNorm.bias   | UNEXPECTED |  |
predictions.dense.weight     | UNEXPECTED |  |
predictions.bias             | UNEXPECTED |  |
predictions.dense.bias       | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

ALBERT embeddings shape: torch.Size([3883, 768])

In [28]:
#E_items for ALBERT
E_all3 = F.normalize(item_emb3, p=2, dim=1)

E_items3 = torch.empty((num_items, E_all3.shape[1]), dtype=E_all3.dtype)
for item_idx in range(num_items):
  mid = idx2item[item_idx]
  row = movieid_to_row.get(mid, None)
  if row is None:
    E_items3[item_idx] = 0
  else:
    E_items3[item_idx] = E_all3[row]

albert_model = BertContentModel(E_items3)
results_albert = eval_model(albert_model, X_ui, test, K=10)
print("ALBERT results:", results_albert)

ALBERT results: {'Recall@K': 0.007292011932383162, 'NDCG@K': 0.0036622119929969276, 'Users': 6034}

In [29]:
#model comparison
comparison = pd.DataFrame([
    {"Model": "BERT base", **results_bert},
    {"Model": "DistilBERT", **results_distil},
    {"Model": "ALBERT", **results_albert},
])
print(comparison.to_string(index=False))

     Model  Recall@K   NDCG@K  Users
 BERT base  0.015578 0.007848   6034
DistilBERT  0.016904 0.007356   6034
    ALBERT  0.007292 0.003662   6034